/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ilemo.viewer.view;

import java.awt.Color;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.DefaultFocusManager;
import javax.swing.FocusManager;
import javax.swing.ToolTipManager;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import lk.ilemo.viewer.view.other.Email;
import lk.ilemo.viewer.view.panles.Desktop;

/**
 *
 * @author Chamindu_Appuhamy
 */
public class EmailSender extends javax.swing.JFrame {
    private Viewer viewer;
    /**
     * Creates new form EmailSender
     */
    public EmailSender() {
        initComponents();
        //this.viewer=viewer;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    UIManager.put("ToolTip.background", new Color(0, 0, 0, 200));
                    UIManager.put("ToolTip.border", new EmptyBorder(5, 5, 5, 5));
                    UIManager.put("ToolTip.foreground", new Color(255, 255, 255));//ToollTipConfugeration
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlePnl = new javax.swing.JPanel();
        titleText = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        myEmailAdress = new javax.swing.JTextField();
        RecEmailAdress = new javax.swing.JTextField();
        emailSubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmailMessage = new javax.swing.JTextArea();
        emailSendLbl = new javax.swing.JLabel();
        myPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titlePnl.setBackground(new java.awt.Color(0, 51, 204));

        titleText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleText.setForeground(new java.awt.Color(255, 255, 255));
        titleText.setText("Viewer Email Sender");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/Gmail.png"))); // NOI18N

        javax.swing.GroupLayout titlePnlLayout = new javax.swing.GroupLayout(titlePnl);
        titlePnl.setLayout(titlePnlLayout);
        titlePnlLayout.setHorizontalGroup(
            titlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePnlLayout.setVerticalGroup(
            titlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleText)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Your Email Adress");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Subject");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("To");

        myEmailAdress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 51, 153)));
        myEmailAdress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                myEmailAdressKeyPressed(evt);
            }
        });

        RecEmailAdress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 51, 153)));
        RecEmailAdress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RecEmailAdressKeyPressed(evt);
            }
        });

        emailSubject.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 51, 153)));
        emailSubject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailSubjectKeyPressed(evt);
            }
        });

        EmailMessage.setColumns(20);
        EmailMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailMessage.setForeground(new java.awt.Color(102, 102, 102));
        EmailMessage.setRows(5);
        EmailMessage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 102, 153)));
        jScrollPane1.setViewportView(EmailMessage);

        emailSendLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/EmailSend.png"))); // NOI18N
        emailSendLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailSendLblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailSendLblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailSendLblMouseReleased(evt);
            }
        });

        myPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 51, 153)));
        myPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                myPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RecEmailAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(emailSubject)
                            .addComponent(myEmailAdress)
                            .addComponent(myPassword, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(18, 18, 18)
                .addComponent(emailSendLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titlePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(myEmailAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(myPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RecEmailAdress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(emailSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailSendLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailSendLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailSendLblMousePressed
        emailSendLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/EmailSendFill.png"))); // NOI18N
    }//GEN-LAST:event_emailSendLblMousePressed

    private void emailSendLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailSendLblMouseReleased
        emailSendLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/EmailSend.png"))); // NOI18N
    }//GEN-LAST:event_emailSendLblMouseReleased

    private void emailSendLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailSendLblMouseClicked
       String myEmail=myEmailAdress.getText();
       String myPass=String.valueOf(myPassword.getText());
       String recEmailAdress=RecEmailAdress.getText();
       String subject=emailSubject.getText();
       String msg=EmailMessage.getText();
        Email email=new Email();
        try {
           boolean generateAndSendEmail = email.generateAndSendEmail(recEmailAdress, subject, msg, myEmail, myPass);
           final ToolTipManager ttmt = ToolTipManager.sharedInstance();
                final int oldDela= ttmt.getInitialDelay();
                ttmt.setInitialDelay(0);
                ttmt.mouseMoved(new MouseEvent(titlePnl, 0, 0, 0,
                        0, 0, // X-Y of the mouse for the tool tip
                        0, false));//ToolTip Auto DisplayMode
               titleText.setToolTipText("Sending.....");
               Thread.sleep(500);
           if(generateAndSendEmail){
               final ToolTipManager ttm = ToolTipManager.sharedInstance();
                final int oldDelay = ttm.getInitialDelay();
                ttm.setInitialDelay(0);
                ttm.mouseMoved(new MouseEvent(titlePnl, 0, 0, 0,
                        0, 0, // X-Y of the mouse for the tool tip
                        0, false));//ToolTip Auto DisplayMode
               titleText.setToolTipText("Email Send Successfully....");
           }
        } catch (MessagingException ex) {
            final ToolTipManager ttm = ToolTipManager.sharedInstance();
                final int oldDelay = ttm.getInitialDelay();
                ttm.setInitialDelay(0);
                ttm.mouseMoved(new MouseEvent(titlePnl, 0, 0, 0,
                        0, 0, // X-Y of the mouse for the tool tip
                        0, false));//ToolTip Auto DisplayMode
               titleText.setToolTipText("Problem Sending....");
        } catch (InterruptedException ex) {
            Logger.getLogger(EmailSender.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_emailSendLblMouseClicked

    private void myEmailAdressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_myEmailAdressKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!myEmailAdress.getText().isEmpty()){
                myPassword.requestFocus();
            }else{
                final ToolTipManager ttm = ToolTipManager.sharedInstance();
                final int oldDelay = ttm.getInitialDelay();
                ttm.setInitialDelay(0);
                ttm.mouseMoved(new MouseEvent(myEmailAdress, 0, 0, 0,
                        0, 0, // X-Y of the mouse for the tool tip
                        0, false));//ToolTip Auto DisplayMode
               myEmailAdress.setToolTipText("Please Fill This Field....");
            }
        }
    }//GEN-LAST:event_myEmailAdressKeyPressed

    private void myPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_myPasswordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!String.valueOf(myPassword.getText()).isEmpty()){
                RecEmailAdress.requestFocus();
            }else{
                final ToolTipManager ttm = ToolTipManager.sharedInstance();
                final int oldDelay = ttm.getInitialDelay();
                ttm.setInitialDelay(0);
                ttm.mouseMoved(new MouseEvent(myPassword, 0, 0, 0,
                        0, 0, // X-Y of the mouse for the tool tip
                        0, false));//ToolTip Auto DisplayMode
               myPassword.setToolTipText("Please Fill This Field....");
            }
        }
    }//GEN-LAST:event_myPasswordKeyPressed

    private void RecEmailAdressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RecEmailAdressKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!RecEmailAdress.getText().isEmpty()){
                emailSubject.requestFocus();
            }else{
                final ToolTipManager ttm = ToolTipManager.sharedInstance();
                final int oldDelay = ttm.getInitialDelay();
                ttm.setInitialDelay(0);
                ttm.mouseMoved(new MouseEvent(RecEmailAdress, 0, 0, 0,
                        0, 0, // X-Y of the mouse for the tool tip
                        0, false));//ToolTip Auto DisplayMode
               RecEmailAdress.setToolTipText("Please Fill This Field....");
            }
        }
    }//GEN-LAST:event_RecEmailAdressKeyPressed

    private void emailSubjectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailSubjectKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!emailSubject.getText().isEmpty()){
                EmailMessage.requestFocus();
            }else{
                final ToolTipManager ttm = ToolTipManager.sharedInstance();
                final int oldDelay = ttm.getInitialDelay();
                ttm.setInitialDelay(0);
                ttm.mouseMoved(new MouseEvent(emailSubject, 0, 0, 0,
                        0, 0, // X-Y of the mouse for the tool tip
                        0, false));//ToolTip Auto DisplayMode
               emailSubject.setToolTipText("Please Fill This Field....");
            }
        }
    }//GEN-LAST:event_emailSubjectKeyPressed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
//        viewer.setKeyboardFocusManagerSignal(0);
    }//GEN-LAST:event_formWindowIconified

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//        viewer.setKeyboardFocusManagerSignal(0);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
//        viewer.setKeyboardFocusManagerSignal(1);
    }//GEN-LAST:event_formWindowDeiconified

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new EmailSender().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea EmailMessage;
    private javax.swing.JTextField RecEmailAdress;
    private javax.swing.JLabel emailSendLbl;
    private javax.swing.JTextField emailSubject;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField myEmailAdress;
    private javax.swing.JPasswordField myPassword;
    private javax.swing.JPanel titlePnl;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
