/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ilemo.viewer.view;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.SourceDataLine;
import javax.sound.sampled.TargetDataLine;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.JavaSoundAudioDevice;
import javazoom.jl.player.Player;
import lk.ilemo.viewer.observer.ObsaverImpl;
import lk.ilemo.viewer.service.custom.Broker;
import lk.ilemo.viewer.service.other.ViewerFileWriter;
import static lk.ilemo.viewer.view.ViewerVideoChatServer.getAudioFormat;
import lk.ilemo.viewer.view.utils.PlayThread;
import lk.ilemo.viewer.view.utils.RecordThread;
import static sun.audio.AudioPlayer.player;

/**
 *
 * @author Chamindu_Appuhamy
 */
public class ViewerVoiceChatServer extends javax.swing.JFrame {

    private Broker broker;
    public int Signal = 2;
    /**
     * ************Client Utils*******************************
     */
    public int port_Srrver = 8889;
    public String add_Server = "192.168.8.100";
    TargetDataLine audio_in2;
    RecordThread r = new RecordThread();//This Object is Used to send Voice Data to the connected Server(Partner) 
    /**
     * *************Server Utiles*****************************
     */
    public int port = 8889;
    public SourceDataLine audio_in;
    PlayThread p = new PlayThread();

    private int TimerSignal = 1;
    private Player player = null;
    private ObsaverImpl impl;
    private String callerName;
    
    /**
     * Creates new form ViewerVoiceChatController
     */
    public ViewerVoiceChatServer(Broker broker, int obj, ObsaverImpl impl) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.broker = broker;
        this.impl = impl;
        if (obj == 1) {
            String ipAddress = broker.getControllerClientDto().getIPAddress();
            String[] split = ipAddress.split("/");
            this.add_Server = split[1];
            callerNameLbl.setText(broker.getControllerClientDto().getUserComputerName());
        } else if (obj == 0) {
            this.add_Server = broker.getServerClientDto().getIPAddress();
            callerNameLbl.setText(broker.getServerClientDto().getUserComputerName());
            callerName= broker.getServerClientDto().getUserComputerName();
//            String[] split = ipAddress.split("/");
//            this.add_Server=split[1];
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        detailPnl = new javax.swing.JPanel();
        callerNameLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        answerLbl = new javax.swing.JLabel();
        rejectLbl = new javax.swing.JLabel();
        endCallLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Viewer Voice");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/callDsh.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        detailPnl.setBackground(new java.awt.Color(0, 204, 255));

        callerNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        callerNameLbl.setForeground(new java.awt.Color(153, 153, 153));
        callerNameLbl.setText("User Name");

        timeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timeLbl.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout detailPnlLayout = new javax.swing.GroupLayout(detailPnl);
        detailPnl.setLayout(detailPnlLayout);
        detailPnlLayout.setHorizontalGroup(
            detailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPnlLayout.createSequentialGroup()
                .addGroup(detailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(callerNameLbl))
                    .addGroup(detailPnlLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(timeLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailPnlLayout.setVerticalGroup(
            detailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(callerNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/CallUserProfile.png"))); // NOI18N

        answerLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/Answer.png"))); // NOI18N
        answerLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answerLblMouseClicked(evt);
            }
        });

        rejectLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/reject.png"))); // NOI18N
        rejectLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rejectLblMouseClicked(evt);
            }
        });

        endCallLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endCallLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(detailPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(answerLbl)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endCallLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(rejectLbl)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rejectLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(answerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addComponent(endCallLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerLblMouseClicked
        //if (Signal != 0) {
            Signal = 1;
//        try {
//            Thread.sleep(100);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(Level.SEVERE, null, ex);
//        }
            answerLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            rejectLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            endCallLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/endCall.png")));

            initAudio_Client();
            init_Audio();
            timer();
            player.close();
        //}

    }//GEN-LAST:event_answerLblMouseClicked

    private void rejectLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectLblMouseClicked
        Signal = 0;
        try {
            ViewerFileWriter.callLoggerFileWriter("",callerName,ViewerFileWriter.callType.REJECTCALL);
        } catch (IOException ex) {
            Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(Level.SEVERE, null, ex);
        }
        //impl.VCall = null;
        //impl.callerCount=0;
        //r.byte_buffer = new byte[0];
        player.close();
        disposeMe();
    }//GEN-LAST:event_rejectLblMouseClicked

    private void endCallLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endCallLblMouseClicked
        impl.VCall = null;
        try {
            ViewerFileWriter.callLoggerFileWriter("",callerName,ViewerFileWriter.callType.ANSWERCALL);
        } catch (IOException ex) {
            Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(Level.SEVERE, null, ex);
        }
        disposeMe();
    }//GEN-LAST:event_endCallLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewerVoiceChatServer().setVisible(true);
//            }
//        });
    }

    public void play() {
        try {
            JavaSoundAudioDevice javaSoundAudioDevice = new JavaSoundAudioDevice();
            FileInputStream fis = new FileInputStream("D:\\2nd Semester Project\\Project\\ViewerClient\\src\\lk\\ilemo\\viewer\\other\\RingTone.mp3");
            BufferedInputStream bis = new BufferedInputStream(fis);
            player = new javazoom.jl.player.Player(bis, javaSoundAudioDevice);
            long songTotal = fis.available();
        } catch (FileNotFoundException ex) {

        } catch (JavaLayerException ex) {

        } catch (IOException ex) {

        }
        new Thread() {
            @Override
            public void run() {
                try {
                    player.play();
                } catch (JavaLayerException ex) {

                }
            }
        }.start();
    }

    private void timer() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                int s = 0;
                int m = 0;
                int h = 0;
                while (TimerSignal != 0) {
                    timeLbl.setText("" + h + "." + m + "." + s);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ViewerVoiceChatController.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    s++;
                    if (s == 60) {
                        m++;
                        s = 0;
                    } else if (m == 60) {
                        h++;
                        m = 0;
                    }
                }
            }
        }).start();
    }

    public void init_Audio() {
        AudioFormat format = getAudioFormat();
        DataLine.Info info_out = new DataLine.Info(SourceDataLine.class, format);
        if (!AudioSystem.isLineSupported(info_out)) {
            System.out.println("NOT SUPPORT....");
            System.exit(0);
        }
        try {
            audio_in = (SourceDataLine) AudioSystem.getLine(info_out);
            audio_in.open();
            audio_in.start();
            p.VchatServer = this;
            p.din = new DatagramSocket(port);
            p.audio_out = audio_in;
            p.Server_Voice = true;
            p.start();
        } catch (LineUnavailableException ex) {
            Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void initAudio_Client() {
        AudioFormat format = getAudioFormat();
        DataLine.Info info = new DataLine.Info(TargetDataLine.class, format);
        if (!AudioSystem.isLineSupported(info)) {
            System.out.println("NOT SUPPORT..");
            System.exit(0);
        }
        try {
            audio_in2 = (TargetDataLine) AudioSystem.getLine(info);
            audio_in2.open();
            audio_in2.start();

            InetAddress inet = InetAddress.getByName(add_Server);
            r.audio_in = audio_in2;
            r.dout = new DatagramSocket();
            r.server_ip = inet;
            r.server_port = port_Srrver;
            r.Client_Voice = true;
            r.start();
        } catch (LineUnavailableException ex) {
            Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(ViewerVoiceChatServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void disposeMe() {
        p.Server_Voice = false;
        r.Client_Voice = false;
        Signal = 2;
        r.byte_buffer = new byte[0];
        TimerSignal = 0;
        player.close();
        //impl.VCall=null;
        this.setVisible(false);
    }
  

    /**
     *
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLbl;
    private javax.swing.JLabel callerNameLbl;
    private javax.swing.JPanel detailPnl;
    private javax.swing.JLabel endCallLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel rejectLbl;
    private javax.swing.JLabel timeLbl;
    // End of variables declaration//GEN-END:variables

}
