/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ilemo.viewer.view;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.MalformedURLException;
import java.net.UnknownHostException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ilemo.viewer.connecter.ServerConnecter;
import lk.ilemo.viewer.controller.ClientController;
import lk.ilemo.viewer.dto.UserDTO;
import lk.ilemo.viewer.observer.ObsaverImpl;
import lk.ilemo.viewer.service.custom.UserService;
import lk.ilemo.viewer.view.panles.Desktop;
import lk.ilemo.viewer.view.panles.Meeting;

/**
 *
 * @author Chamindu_Appuhamy
 */
public class ViewerMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewerMain
     */
    private String myId = "12345678";
    private String password = "6yt54f9p";

    public ViewerMain() {
        initComponents();
        setLocationRelativeTo(null);
        setUp();//Setting Connection
        setDesktopFunction();//Setting Remote DesktopFunction
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        meetingLblBtn = new javax.swing.JLabel();
        desktopLblBtn = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        connectionStatusLbl = new javax.swing.JLabel();
        loadingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(70, 51, 255));

        meetingLblBtn.setBackground(new java.awt.Color(255, 255, 255));
        meetingLblBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        meetingLblBtn.setForeground(new java.awt.Color(255, 255, 255));
        meetingLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/group.png"))); // NOI18N
        meetingLblBtn.setText("M E E T I N G S");
        meetingLblBtn.setToolTipText("");
        meetingLblBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meetingLblBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                meetingLblBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                meetingLblBtnMouseReleased(evt);
            }
        });

        desktopLblBtn.setBackground(new java.awt.Color(255, 255, 255));
        desktopLblBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        desktopLblBtn.setForeground(new java.awt.Color(255, 255, 255));
        desktopLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/desktoparr.png"))); // NOI18N
        desktopLblBtn.setText("D E S K T O P");
        desktopLblBtn.setToolTipText("");
        desktopLblBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desktopLblBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desktopLblBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                desktopLblBtnMouseReleased(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(desktopLblBtn)
                .addGap(272, 272, 272)
                .addComponent(meetingLblBtn)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(529, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(455, 455, 455)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(desktopLblBtn)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(meetingLblBtn)
                        .addGap(31, 31, 31))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator2)
                    .addContainerGap()))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        connectionStatusLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connectionStatusLbl.setForeground(new java.awt.Color(255, 204, 0));
        connectionStatusLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/smallconnectiondots.png"))); // NOI18N
        connectionStatusLbl.setText("Connecting....");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(connectionStatusLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(connectionStatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        loadingPanel.setBackground(new java.awt.Color(153, 153, 153));
        loadingPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desktopLblBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopLblBtnMouseClicked
        setDesktopFunction();
        System.out.println("set");
    }//GEN-LAST:event_desktopLblBtnMouseClicked

    private void desktopLblBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopLblBtnMousePressed
        desktopLblBtn.setForeground(new java.awt.Color(51, 153, 255));
        //desktopLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/bluedesktoparr.png"))); // NOI18N
        //desktopLblBtn.setText("D E S K T O P");
    }//GEN-LAST:event_desktopLblBtnMousePressed

    private void desktopLblBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopLblBtnMouseReleased
       desktopLblBtn.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_desktopLblBtnMouseReleased

    private void meetingLblBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meetingLblBtnMousePressed
        meetingLblBtn.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_meetingLblBtnMousePressed

    private void meetingLblBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meetingLblBtnMouseReleased
        meetingLblBtn.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_meetingLblBtnMouseReleased

    private void meetingLblBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meetingLblBtnMouseClicked
        try {
            Meeting d = new Meeting();
            d.setVisible(true);
            loadingPanel.removeAll();
            loadingPanel.add(d);
            loadingPanel.repaint();
            loadingPanel.revalidate();
        } catch (IOException ex) {
            Logger.getLogger(ViewerMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_meetingLblBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connectionStatusLbl;
    private javax.swing.JLabel desktopLblBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel loadingPanel;
    private javax.swing.JLabel meetingLblBtn;
    // End of variables declaration//GEN-END:variables
    private void setDesktopFunction() {
        Desktop d = new Desktop(myId, password);
        d.setVisible(true);
        loadingPanel.removeAll();
        loadingPanel.add(d);
        loadingPanel.repaint();
        loadingPanel.revalidate();
    }

    private void setUp() {
        try {
            
            InetAddress address;
            InetAddress localHost = InetAddress.getLocalHost();
            UserDTO dto = new UserDTO(localHost.getHostName(), Inet4Address.getLocalHost().toString(), Toolkit.getDefaultToolkit().getScreenSize());
            boolean loginToViewerServer = ClientController.loginToViewerServer(dto,new ObsaverImpl(this));
            if (loginToViewerServer) {
                connectionStatusLbl.setForeground(new java.awt.Color(0, 153, 0));
                connectionStatusLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/greenConnectionDots.png"))); // NOI18N
                connectionStatusLbl.setText("Connected");
                UserDTO loginDetails = ClientController.getLoginDetails();
                myId = loginDetails.getUserComputerName();
                password = loginDetails.getPassword();//GetLogin Password and UserId From Viewer Server
            }
        } catch (NotBoundException ex) {
            System.out.println("not bound exception");
        } catch (MalformedURLException ex) {
            System.out.println("malform exception");
        } catch (RemoteException ex) {
            connectionStatusLbl.setForeground(new java.awt.Color(255, 0, 0));
            connectionStatusLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ilemo/viewer/view/icons/redConnectionDots.png"))); // NOI18N
            connectionStatusLbl.setText("No Connections");//Connection Status
        } catch (UnknownHostException ex) {
            System.out.println("unknown hostname");
        } catch (IOException ex) {
            Logger.getLogger(ViewerMain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
